version: 0.2
phases:
  build:
    commands:
      - echo "Build started on `date`"
artifacts:
  files:
    # This wildcard tells CodeBuild to grab ALL files from your
    # repository and put them in the final .zip artifact.
    - '**/*'
